-- !preview on -- Supabase PostgreSQL schema
-- Blog posts table for the Supabase-backed portfolio blog.
-- Run this in the Supabase SQL editor (Dashboard > SQL Editor).

create table if not exists public.blog_posts (
  id          bigint generated by default as identity primary key,
  title       text not null,
  excerpt     text not null,
  body        text not null,
  category    text not null default 'Tech',
  date        date not null,
  image       text,
  medium_link text,
  tags        text[] not null default '{}',
  read_time   text not null default '5 min read',
  featured    boolean not null default false,
  published   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Anyone (anonymous) may read published posts.
alter table public.blog_posts enable row level security;

create policy "blog_posts public read"
  on public.blog_posts
  for select
  to anon, authenticated
  using (true);

-- Only authenticated users may create, update, or delete posts.
create policy "blog_posts authenticated insert"
  on public.blog_posts
  for insert
  to authenticated
  with check (true);

create policy "blog_posts authenticated update"
  on public.blog_posts
  for update
  to authenticated
  using (true)
  with check (true);

create policy "blog_posts authenticated delete"
  on public.blog_posts
  for delete
  to authenticated
  using (true);

-- ── PROJECTS TABLE ──
create table if not exists public.projects (
  id          bigint generated by default as identity primary key,
  title       text not null,
  category    text not null,
  featured    boolean not null default false,
  impact      text not null default 'production',
  users       text,
  description text not null,
  problem     text,
  approach    text,
  architecture text,
  engineering text[] default '{}',
  result      text,
  tech        text[] default '{}',
  metrics     text[] default '{}',
  image       text,
  github      text,
  live        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.projects enable row level security;

create policy "projects public read"
  on public.projects for select to anon, authenticated using (true);

create policy "projects authenticated write"
  on public.projects for insert to authenticated with check (true);

create policy "projects authenticated update"
  on public.projects for update to authenticated using (true) with check (true);

create policy "projects authenticated delete"
  on public.projects for delete to authenticated using (true);

-- ── SKILLS TABLE ──
create table if not exists public.skills (
  id          bigint generated by default as identity primary key,
  title       text not null,
  skills      text[] not null default '{}',
  description text not null,
  evidence    text,
  "order"     int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.skills enable row level security;

create policy "skills public read"
  on public.skills for select to anon, authenticated using (true);

create policy "skills authenticated write"
  on public.skills for insert to authenticated with check (true);

create policy "skills authenticated update"
  on public.skills for update to authenticated using (true) with check (true);

create policy "skills authenticated delete"
  on public.skills for delete to authenticated using (true);

-- ── TESTIMONIALS TABLE ──
create table if not exists public.testimonials (
  id          bigint generated by default as identity primary key,
  name        text not null,
  role        text not null,
  company     text,
  avatar      text,
  quote       text not null,
  featured    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.testimonials enable row level security;

create policy "testimonials public read"
  on public.testimonials for select to anon, authenticated using (true);

create policy "testimonials authenticated write"
  on public.testimonials for insert to authenticated with check (true);

create policy "testimonials authenticated update"
  on public.testimonials for update to authenticated using (true) with check (true);

create policy "testimonials authenticated delete"
  on public.testimonials for delete to authenticated using (true);

-- ── EXPERIENCE TABLE ──
create table if not exists public.experience (
  id          bigint generated by default as identity primary key,
  title       text not null,
  organization text not null,
  period      text not null,
  type        text not null default 'engineering',
  description text not null,
  highlights  text[] default '{}',
  technologies text[] default '{}',
  metrics     jsonb default '{}',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.experience enable row level security;

create policy "experience public read"
  on public.experience for select to anon, authenticated using (true);

create policy "experience authenticated write"
  on public.experience for insert to authenticated with check (true);

create policy "experience authenticated update"
  on public.experience for update to authenticated using (true) with check (true);

create policy "experience authenticated delete"
  on public.experience for delete to authenticated using (true);

-- ── STATS TABLE ──
create table if not exists public.stats (
  id          bigint generated by default as identity primary key,
  key         text not null unique,
  label       text not null,
  value       text not null,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

alter table public.stats enable row level security;

create policy "stats public read"
  on public.stats for select to anon, authenticated using (true);

create policy "stats authenticated write"
  on public.stats for insert to authenticated with check (true);

create policy "stats authenticated update"
  on public.stats for update to authenticated using (true) with check (true);

create policy "stats authenticated delete"
  on public.stats for delete to authenticated using (true);
