-- Blog posts table for the Supabase-backed portfolio blog.
-- Run this in the Supabase SQL editor (Dashboard > SQL Editor).

create table if not exists public.blog_posts (
  id          bigint generated by default as identity primary key,
  title       text not null,
  excerpt     text not null,
  body        text not null,
  category    text not null default 'Tech',
  date        date not null,
  image       text,
  medium_link text,
  tags        text[] not null default '{}',
  read_time   text not null default '5 min read',
  featured    boolean not null default false,
  created_at  timestamptz not null default now()
);

-- Anyone (anonymous) may read published posts.
alter table public.blog_posts enable row level security;

create policy "blog_posts public read"
  on public.blog_posts
  for select
  to anon, authenticated
  using (true);

-- Only authenticated users may create, update, or delete posts.
create policy "blog_posts authenticated insert"
  on public.blog_posts
  for insert
  to authenticated
  with check (true);

create policy "blog_posts authenticated update"
  on public.blog_posts
  for update
  to authenticated
  using (true)
  with check (true);

create policy "blog_posts authenticated delete"
  on public.blog_posts
  for delete
  to authenticated
  using (true);
