-- Scored practice exercises (quiz-style, auto-graded) for BOTH courses.
--   * Python (11 weeks): three published questions per week, attached to the
--     new fun-lab lessons (lesson_number 6 = Lab, 7 = Bug Hunt, 8 = Mission).
--   * C++ (24 weeks): three published questions per week, attached to the new
--     Checkpoint lesson (lesson_number 2).
-- Types used: multiple_choice (choices are plain strings; correct_answer must
-- equal the chosen string) and true_false (correct_answer is 'true'/'false').
-- Scoring happens via academy_submit_objective_answer, which compares
-- lower(trim(correct_answer)) = lower(trim(submitted_answer)).
-- Idempotent: guarded by "not exists (same lesson + title)". Safe to re-run.

-- ---------------------------------------------------------------------------
-- Python course
-- ---------------------------------------------------------------------------
insert into public.academy_exercises (
  lesson_id, title, instructions, starter_code, difficulty,
  expected_concepts, hints, explanation, question_type, choices,
  correct_answer, attempt_limit, published, sort_order
)
select
  lessons.id,
  exercise.title,
  exercise.instructions,
  '',
  exercise.difficulty,
  exercise.expected_concepts,
  exercise.hints,
  exercise.explanation,
  exercise.question_type,
  exercise.choices,
  exercise.correct_answer,
  3,
  true,
  exercise.sort_order
from public.academy_lessons lessons
join public.academy_weeks weeks on weeks.id = lessons.week_id
join public.academy_courses course on course.id = weeks.course_id
join (
  values
    -- Week 1: Starting to Code
    (1, 6, 'What is a variable?', 'What is stored inside a variable?',
     'beginner', array['variables', 'values'],
     array['A variable is a named box.', 'It holds data your program uses.'],
     'Variables are the named boxes that hold your data so print() can reuse it.', 'multiple_choice',
     '["A named box holding a value", "A printed line of text", "A type of keyboard", "An error message"]'::jsonb,
     'A named box holding a value', 1),
    (1, 7, 'Error messages and lines', 'True or false: an error message can point you to the exact line to check.',
     'beginner', array['debugging', 'error messages'],
     array['Error messages name the file and line.', 'Read the message before guessing.'],
     'Error messages are clues: they usually show exactly where to look.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (1, 8, 'Joining a label and a value', 'What does a plus sign (+) do between a label and a variable inside print?',
     'beginner', array['print', 'string joining'],
     array['PLus joins text together.', 'It builds one output line.'],
     'The plus sign joins (concatenates) the label and the variable value into one line.', 'multiple_choice',
     '["Joins them into one line of output", "Adds their numbers", "Starts a new program", "Deletes the variable"]'::jsonb,
     'Joins them into one line of output', 3),
    -- Week 2: Making Decisions
    (2, 6, 'Equality operator', 'Which operator checks whether two values are equal?',
     'beginner', array['==', 'comparison'],
     array['One equals sign assigns.', 'Two equal signs compare.'],
     'Use two equal signs (==) to compare values; a single = assigns.', 'multiple_choice',
     '["=", "==", "=>", "!"]'::jsonb,
     '==', 1),
    (2, 7, 'First matching branch', 'True or false: in an if/elif/else chain, the first matching branch is the only one that runs.',
     'beginner', array['if/elif/else', 'branch order'],
     array['The chain checks from the top.', 'The first true branch wins.'],
     'Only the first branch whose condition is true runs; the rest are skipped.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (2, 8, 'The and operator', 'What does and do in a condition like happy and hungry?',
     'beginner', array['and', 'conditions'],
     array['Both sides must hold.', 'It combines two tests.'],
     'With and, the whole condition is true only when BOTH parts are true.', 'multiple_choice',
     '["Both parts must be true for the whole to be true", "Either part can be true", "It prints both values", "It asks the user a question"]'::jsonb,
     'Both parts must be true for the whole to be true', 3),
    -- Week 3: Repeating & Organizing Data
    (3, 6, 'Loop over a list', 'A for loop runs its body once for every item. For a list of 4 items, how many times does it run?',
     'beginner', array['for loop', 'lists'],
     array['Count the items.', 'The body repeats once per item.'],
     'A for loop visits each item in the list exactly once.', 'multiple_choice',
     '["4", "3", "1", "Until the program stops"]'::jsonb,
     '4', 1),
    (3, 7, 'Off by one', 'True or false: an off-by-one error happens when a loop repeats the wrong number of times.',
     'beginner', array['off-by-one', 'loops'],
     array['Count the real iterations.', 'One too many or one too few is off-by-one.'],
     'Off-by-one bugs repeat once too often or once too few.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (3, 8, 'Counting passing scores', 'Which variable would you add to count passing scores while looping?',
     'beginner', array['counters', 'loops'],
     array['A counter starts at zero.', 'It grows by one on each pass.'],
     'A counter variable that starts at 0 and grows by 1 on each matching item gives you the count.', 'multiple_choice',
     '["A counter that grows by 1 on each pass", "A second list", "A new loop", "A dictionary"]'::jsonb,
     'A counter that grows by 1 on each pass', 3),
    -- Week 4: Reusable Code & Dictionaries
    (4, 6, 'What return does', 'What does the return statement do inside a function?',
     'beginner', array['return', 'functions'],
     array['Return hands a value back.', 'Print only shows it on screen.'],
     'return sends a value back to whoever called the function so it can be reused.', 'multiple_choice',
     '["Hands a value back to the caller", "Prints a value on screen", "Ends the whole program", "Starts a new file"]'::jsonb,
     'Hands a value back to the caller', 1),
    (4, 7, 'Printing but not returning', 'True or false: a function that prints an answer but returns nothing hands None to the caller.',
     'developing', array['None', 'return vs print'],
     array['print shows values.', 'Without return the caller gets None.'],
     'A function with no return statement hands None to the caller, so math on its result fails.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (4, 8, 'Reading a dictionary', 'In a dictionary, how do you find a value you stored?',
     'beginner', array['dictionaries', 'keys'],
     array['Dictionaries are found by label.', 'A key names the value.'],
     'You read a dictionary value by its key or label, not by its position in a list.', 'multiple_choice',
     '["By its key or label", "By its position in a list", "By its colour", "By its file name"]'::jsonb,
     'By its key or label', 3),
    -- Week 5: Files & Errors
    (5, 6, 'File modes', 'Which mode appends text to the end of a file without erasing what is already there?',
     'beginner', array['files', 'modes'],
     array['w wipes the file.', 'a keeps the history and appends.'],
     'Mode a appends to the end of a file; mode w overwrites it completely.', 'multiple_choice',
     '["a", "w", "r", "x"]'::jsonb,
     'a', 1),
    (5, 7, 'int() on empty text', 'True or false: int() on empty text raises a ValueError rather than a FileNotFoundError.',
     'developing', array['ValueError', 'exceptions'],
     array['Each error type has a name.', 'The error name tells you what went wrong.'],
     'A bad conversion raises ValueError; a missing file raises FileNotFoundError.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (5, 8, 'Why try/except', 'Why use try/except when loading a saved file?',
     'beginner', array['try/except', 'files'],
     array['The file may not exist yet.', 'The program should not crash.'],
     'The first run often has no file yet, so a missing file should start from a default instead of crashing.', 'multiple_choice',
     '["A missing file is normal the first run and should not crash the program", "To make the file faster to open", "To rename the file", "Because the computer demands it"]'::jsonb,
     'A missing file is normal the first run and should not crash the program', 3),
    -- Week 6: Meet Your Data
    (6, 6, 'A row of data', 'In pure Python, what is one row of a small dataset commonly stored as?',
     'beginner', array['records', 'list of dictionaries'],
     array['Each person is one row.', 'A label-per-field structure.'],
     'One row is a dictionary with the same keys for every field, collected in a list.', 'multiple_choice',
     '["A dictionary with the same keys for each field", "A single number", "A printed line", "A function"]'::jsonb,
     'A dictionary with the same keys for each field', 1),
    (6, 7, 'KeyError', 'True or false: row["hours"] raises KeyError if that key is missing from the record.',
     'developing', array['KeyError', 'data quality'],
     array['A missing key raises an error.', 'Read the key name in the message.'],
     'Accessing a key that does not exist raises a KeyError that names the missing key.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (6, 8, 'Health check first', 'What should a health check report on a dataset first?',
     'beginner', array['data quality', 'missing values'],
     array['Look for blanks.', 'Report min and max.'],
     'A health check counts rows, finds missing values, and shows the range before any analysis.', 'multiple_choice',
     '["Missing values and the range of each column", "The colour of the screen", "Which student writes fastest", "The size of the font"]'::jsonb,
     'Missing values and the range of each column', 3),
    -- Week 7: Exploring Data
    (7, 6, 'Text chart bars', 'In a text chart, what does the number of repeated # characters show?',
     'beginner', array['charts', 'text scaling'],
     array['The bar length matches the value.', 'Bigger values give longer bars.'],
     'Each # is one unit, so the bar length represents the size of the value.', 'multiple_choice',
     '["The size of the value in the data", "The number of bugs", "The length of the label", "The time of day"]'::jsonb,
     'The size of the value in the data', 1),
    (7, 7, 'Dividing by zero', 'True or false: dividing by zero raises a ZeroDivisionError that you should guard against.',
     'developing', array['ZeroDivisionError', 'edge cases'],
     array['An empty list leads to division by zero.', 'Check before you divide.'],
     'Guard empty datasets so an average never divides by zero.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (7, 8, 'Sorting highest first', 'Which call sorts items so the biggest value comes first?',
     'beginner', array['sorted', 'ranking'],
     array['reverse reorders the result.', 'Default sorting is smallest first.'],
     'sorted(items, reverse=True) orders from largest to smallest.', 'multiple_choice',
     '["sorted with reverse set to true", "sorted with reverse set to false", "len", "sum"]'::jsonb,
     'sorted with reverse set to true', 3),
    -- Week 8: What Is AI / ML
    (8, 6, 'What is the target?', 'In a machine learning example, what is the target?',
     'beginner', array['features', 'target'],
     array['It is what you predict.', 'Examples come with known answers.'],
     'The target is the answer the model should predict, like a label of true or false.', 'multiple_choice',
     '["The answer the model should predict", "The number of rows of data", "The name of the file", "A spelling mistake"]'::jsonb,
     'The answer the model should predict', 1),
    (8, 7, 'Data leakage', 'True or false: data leakage happens when a feature already contains the answer.',
     'developing', array['data leakage', 'fair evaluation'],
     array['Features must not reveal the answer.', 'Perfect scores can be a red flag.'],
     'When a feature is really the answer in disguise, the model is cheating and the score is fake.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (8, 8, 'Rules vs learning', 'What does a rule-based classifier use that a learning model discovers on its own?',
     'beginner', array['rule-based', 'machine learning'],
     array['You hand-write the rule.', 'The data suggests the rule.'],
     'You write the rules yourself; machine learning lets the data suggest the rules.', 'multiple_choice',
     '["Rules written by hand", "A bigger screen", "A faster loop", "Louder speakers"]'::jsonb,
     'Rules written by hand', 3),
    -- Week 9: Your First Model
    (9, 6, 'Why held-out data', 'Why do we test a model on rows it never trained on?',
     'beginner', array['train/test split', 'evaluation'],
     array['The test rows are saved.', 'The score must be honest.'],
     'Held-out rows act like an exam the model has not studied, giving a true score.', 'multiple_choice',
     '["To get an honest score of how it will behave on new data", "To make the data bigger", "To use all the rows", "Because the teacher said speed matters"]'::jsonb,
     'To get an honest score of how it will behave on new data', 1),
    (9, 7, 'Fit on test rows', 'True or false: fitting a model on the test rows makes its accuracy look better than it truly is.',
     'developing', array['leakage', 'honest scores'],
     array['Never fit on test data.', 'A fake score looks too good.'],
     'Training on the test rows leaks the answers and inflates accuracy.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (9, 8, 'Model report parts', 'Which parts belong in a short model report?',
     'beginner', array['reports', 'evaluation'],
     array['Say what the data is.', 'State the limits.'],
     'A report covers the data, the split, the accuracy, and at least one honest limitation.', 'multiple_choice',
     '["Data, split, accuracy, and a limitation", "Only the accuracy", "The team name and logo", "The model colour"]'::jsonb,
     'Data, split, accuracy, and a limitation', 3),
    -- Week 10: Build With Less Help
    (10, 6, 'A fair experiment', 'When comparing two feature sets, what should stay the same?',
     'developing', array['feature selection', 'controlled experiments'],
     array['Change only one thing at a time.', 'The test rows must match.'],
     'Keep the model and the test rows identical so only the feature changes.', 'multiple_choice',
     '["The model and the test rows", "The web browser", "The student names", "The file names"]'::jsonb,
     'The model and the test rows', 1),
    (10, 7, 'Overfitting', 'True or false: overfitting means nailing the training data but failing on new data.',
     'developing', array['overfitting', 'generalisation'],
     array['Memorising is not learning.', 'The train/test gap reveals it.'],
     'Overfitting memorises the training rows, so new rows score badly.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (10, 8, 'Tying models', 'Two models tie on accuracy. What else could help you choose?',
     'developing', array['model comparison', 'decision making'],
     array['Look at the hard cases.', 'Simplicity is a feature.'],
     'When accuracy ties, compare behaviour on hard examples and pick the simpler model.', 'multiple_choice',
     '["How each behaves on the hardest example and which is simpler", "Whichever name is shorter", "Whichever printed first", "A coin flip"]'::jsonb,
     'How each behaves on the hardest example and which is simpler', 3),
    -- Week 11: Your Own Project
    (11, 6, 'Success metric', 'Which part of a plan states how you will measure success?',
     'beginner', array['planning', 'metrics'],
     array['Decide the score before you run.', 'Metrics are measurable.'],
     'A success metric like accuracy tells you, up front, what winning looks like.', 'multiple_choice',
     '["A success metric like accuracy", "The list of favourite games", "The file colour", "The loop count"]'::jsonb,
     'A success metric like accuracy', 1),
    (11, 7, 'Pipeline order', 'True or false: in a machine learning pipeline you must split the data before fitting the model.',
     'developing', array['pipeline', 'split before fit'],
     array['Split first.', 'Then fit on train only.'],
     'The pipeline order is prepare, split, fit on train, predict on test.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (11, 8, 'Easy to follow demo', 'What makes a demo script easy to follow?',
     'beginner', array['communication', 'demo structure'],
     array['Keep a clear arc.', 'End with a next step.'],
     'A clear arc of question, data, result, and next step keeps an audience with you.', 'multiple_choice',
     '["A clear arc of question, data, result, and next step", "The longest possible sentences", "No mention of limitations", "Extra polish and noise"]'::jsonb,
     'A clear arc of question, data, result, and next step', 3)
) as exercise(week_number, lesson_number, title, instructions, difficulty, expected_concepts, hints, explanation, question_type, choices, correct_answer, sort_order)
  on exercise.week_number = weeks.week_number
  and lessons.lesson_number = exercise.lesson_number
where course.slug = 'python-for-ai-machine-learning'
  and not exists (
    select 1 from public.academy_exercises existing
    where existing.lesson_id = lessons.id and existing.title = exercise.title
  );

-- ---------------------------------------------------------------------------
-- C++ course
-- ---------------------------------------------------------------------------
insert into public.academy_exercises (
  lesson_id, title, instructions, starter_code, difficulty,
  expected_concepts, hints, explanation, question_type, choices,
  correct_answer, attempt_limit, published, sort_order
)
select
  lessons.id,
  exercise.title,
  exercise.instructions,
  '',
  exercise.difficulty,
  exercise.expected_concepts,
  exercise.hints,
  exercise.explanation,
  exercise.question_type,
  exercise.choices,
  exercise.correct_answer,
  3,
  true,
  exercise.sort_order
from public.academy_lessons lessons
join public.academy_weeks weeks on weeks.id = lessons.week_id
join public.academy_courses course on course.id = weeks.course_id
join (
  values
    -- Week 1: Algorithms & first program
    (1, 2, 'Input to output', 'In the Input, Processing, Output pattern, what comes between Input and Output?',
     'beginner', array['IPO', 'processing'],
     array['The middle step changes the input.', 'It is the thinking step.'],
     'Processing is the step that turns the input into the output.', 'multiple_choice',
     '["Processing", "Storage only", "Printing", "Rebooting"]'::jsonb,
     'Processing', 1),
    (1, 2, 'What a flowchart is', 'True or false: a flowchart is a step-by-step picture of how a program flows.',
     'beginner', array['flowcharts', 'design'],
     array['Ovals, rectangles, diamonds.', 'It shows the flow of steps.'],
     'Flowcharts draw the steps and decisions of a routine before you code it.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (1, 2, 'Printing a line', 'Which statement prints a line to the console in C++?',
     'beginner', array['cout', 'console'],
     array['The stream operator faces the value.', 'The statement ends with a semicolon.'],
     'cout with two less-than signs sends text to the console.', 'multiple_choice',
     '["cout with two less-than signs", "printLine", "display", "echo on"]'::jsonb,
     'cout with two less-than signs', 3),
    -- Week 2: Data types
    (2, 2, 'Integer division', 'What does 7 / 2 print when both numbers are int?',
     'beginner', array['int', 'division'],
     array['Whole-number division truncates.', 'A decimal operand forces fractions.'],
     'Integer division drops the fraction, so 7 / 2 is 3.', 'multiple_choice',
     '["3", "3.5", "0", "error"]'::jsonb,
     '3', 1),
    (2, 2, 'Storing fractions', 'True or false: a double can store fractional values.',
     'beginner', array['double', 'floats'],
     array['A double holds decimals.', 'An int truncates them.'],
     'Use double whenever measurements need fractional precision.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (2, 2, 'Button state type', 'Which type best stores whether a button is pressed?',
     'beginner', array['bool', 'types'],
     array['Yes/no fits two values.', 'True or false is the right shape.'],
     'A bool stores true or false, exactly right for a pressed or unpressed button.', 'multiple_choice',
     '["bool", "char", "int", "double"]'::jsonb,
     'bool', 3),
    -- Week 3: Decisions
    (3, 2, 'Branch order', 'In an if/else chain, which branch should be tested first?',
     'beginner', array['branch order', 'if/else'],
     array['The first true branch wins.', 'Narrow checks must come first.'],
     'Test the hardest-to-match, most specific condition first so broad checks do not swallow it.', 'multiple_choice',
     '["The most specific and hardest to match", "The easiest one", "The shortest one", "The last one written"]'::jsonb,
     'The most specific and hardest to match', 1),
    (3, 2, 'Broad before narrow', 'True or false: checking a broad condition like over 50 before over 75 hides the distinction branch.',
     'developing', array['branch order', 'boundaries'],
     array['The first match runs.', 'Narrowest must come first.'],
     'A broad check catches values for the narrow case first, so the specific branch never runs.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (3, 2, 'Boundary tests', 'What is the best set of values to test at a decision boundary?',
     'beginner', array['boundary values', 'testing'],
     array['Boundaries hide off-by-one bugs.', 'Test exactly on the edge.'],
     'Test boundary values like exactly 50 and 75 to prove the edges behave.', 'multiple_choice',
     '["Boundary values like exactly 50 and 75", "Only the biggest number", "Only zero", "No values at all"]'::jsonb,
     'Boundary values like exactly 50 and 75', 3),
    -- Week 4: Loops
    (4, 2, 'May run zero times', 'Which loop checks its condition first and may run zero times?',
     'beginner', array['while', 'loops'],
     array['The check comes before the body.', 'Some loops verify first.'],
     'A while loop tests before running, so it can run zero times.', 'multiple_choice',
     '["while", "do-while", "repeat", "forever"]'::jsonb,
     'while', 1),
    (4, 2, 'Off-by-one loops', 'True or false: using less-than-or-equal where a less-than was meant often repeats the loop one extra time.',
     'developing', array['off-by-one', 'loop bounds'],
     array['Compare the last iteration.', 'One extra pass is a bug.'],
     'A misplaced boundary repeats one time too many, the classic off-by-one.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (4, 2, 'Runs at least once', 'Which loop runs its body at least once before checking the condition?',
     'beginner', array['do-while', 'loops'],
     array['The body comes first.', 'The test comes after.'],
     'A do-while checks after the body, so it always runs at least once.', 'multiple_choice',
     '["do-while", "for", "while", "none of the above"]'::jsonb,
     'do-while', 3),
    -- Week 5: Functions
    (5, 2, 'Why testable', 'Why is a function with a return value easier to test?',
     'beginner', array['functions', 'testing'],
     array['You can compare the result.', 'Known inputs give known outputs.'],
     'You can call it with a known input and check the return against the known answer.', 'multiple_choice',
     '["You can check it against known answers", "It is longer", "It has no inputs", "It always prints"]'::jsonb,
     'You can check it against known answers', 1),
    (5, 2, 'Unit test trick', 'True or false: testing a function with a value whose answer you already know is a good unit test.',
     'beginner', array['unit tests', 'functions'],
     array['Known answers are proofs.', 'Compute by hand first.'],
     'A unit test uses known inputs and expected outputs, such as average(10, 20) being 15.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (5, 2, 'Function inputs', 'Which part of a function signature lists what data it expects?',
     'beginner', array['parameters', 'signatures'],
     array['The name is not the data.', 'The parentheses hold them.'],
     'The parameters in the signature declare what values the function expects.', 'multiple_choice',
     '["The parameters", "The opening brace", "The return type only", "The filename"]'::jsonb,
     'The parameters', 3),
    -- Week 6: Arrays
    (6, 2, 'First index', 'Array indices in C++ start at what number?',
     'beginner', array['arrays', 'indices'],
     array['Start counting from zero.', 'Index size would be past the end.'],
     'The first element of an array is at index 0 in C++.', 'multiple_choice',
     '["0", "1", "the size of the array", "100"]'::jsonb,
     '0', 1),
    (6, 2, 'Reading past the end', 'True or false: looping to a value equal to the array size reads past the end of the array.',
     'developing', array['bounds', 'arrays'],
     array['Valid indices stop at size minus one.', 'Equal to size is out of range.'],
     'Indices run 0 to size-1, so looping to <= size reads out of bounds.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (6, 2, 'Finding the average', 'To compute the average of n readings, divide the total by what?',
     'beginner', array['averages', 'aggregates'],
     array['The average spreads evenly.', 'The divisor is the count.'],
     'Total divided by the number of readings n gives the average.', 'multiple_choice',
     '["n", "n minus one", "n plus one", "the first reading"]'::jsonb,
     'n', 3),
    -- Week 7: setup/loop, digital pins
    (7, 2, 'Configure once', 'What must you configure exactly once in setup()?',
     'beginner', array['setup()', 'pinMode'],
     array['Pin modes belong at the start.', 'Configuration happens once.'],
     'Every pin you use is configured once with pinMode in setup().', 'multiple_choice',
     '["Every pin you use with pinMode", "The entire loop", "The serial monitor", "Nothing"]'::jsonb,
     'Every pin you use with pinMode', 1),
    (7, 2, 'Pull-up logic', 'True or false: with INPUT_PULLUP, a pressed button reads LOW.',
     'developing', array['INPUT_PULLUP', 'buttons'],
     array['Pull-up inverts the logic.', 'Pressed means LOW.'],
     'INPUT_PULLUP means the idle state reads HIGH and a press reads LOW.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (7, 2, 'Turning on an LED', 'Which call turns a digital output pin on?',
     'beginner', array['digitalWrite', 'outputs'],
     array['Set the pin high.', 'The function writes a level.'],
     'digitalWrite with HIGH drives the pin to its on level.', 'multiple_choice',
     '["digitalWrite with HIGH", "analogRead", "delay", "pinMode with INPUT"]'::jsonb,
     'digitalWrite with HIGH', 3),
    -- Week 8: Analog & thresholds
    (8, 2, 'analogRead range', 'What does analogRead return?',
     'beginner', array['analogRead', 'ADC'],
     array['It maps a voltage to a number.', 'That number has a range.'],
     'analogRead returns a whole number between 0 and 1023.', 'multiple_choice',
     '["A whole number between 0 and 1023", "Only always 5", "A line of text", "Either 0 or 1"]'::jsonb,
     'A whole number between 0 and 1023', 1),
    (8, 2, 'Measured thresholds', 'True or false: a threshold measured from real sensor data beats a number invented beforehand.',
     'beginner', array['calibration', 'thresholds'],
     array['Record first.', 'Then decide.'],
     'Calibrating against real bright and dark readings places the threshold where it belongs.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (8, 2, 'Avoiding flicker', 'Where should you place a light threshold to avoid flicker?',
     'developing', array['flicker', 'thresholds'],
     array['Real values cluster.', 'Pick the quiet gap.'],
     'Place the threshold in the quiet gap between the bright and dark clusters of readings.', 'multiple_choice',
     '["In the quiet gap between bright and dark readings", "Exactly on a single reading", "At the very top of the range", "Below zero"]'::jsonb,
     'In the quiet gap between bright and dark readings', 3),
    -- Week 9: Ultrasonic
    (9, 2, 'How HC-SR04 works', 'The HC-SR04 measures distance using what?',
     'beginner', array['HC-SR04', 'ultrasonic'],
     array['It bounces something off the target.', 'Time-to-year accounts for a round trip.'],
     'It sends a sound pulse and times how long the echo takes to return.', 'multiple_choice',
     '["A pulse of sound and the time to its echo", "A beam of light", "Radio waves to the internet", "A vibration motor"]'::jsonb,
     'A pulse of sound and the time to its echo', 1),
    (9, 2, 'Sense-Think-Act', 'True or false: the SENSE to THINK to ACT pattern describes reading, deciding, and then moving.',
     'beginner', array['SENSE-THINK-ACT', 'robots'],
     array['Read a value.', 'Decide, then move.'],
     'Every robot loop reads an input, decides, then acts on the result.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (9, 2, 'Echo to centimetres', 'Dividing the measured echo time by 58 converts it to what?',
     'developing', array['conversion', 'distance'],
     array['The divisor is a scale factor.', 'The result is a length.'],
     'Dividing the round-trip echo time by 58 gives distance in centimetres.', 'multiple_choice',
     '["Distance in centimetres", "The voltage", "The temperature", "The speed of the robot"]'::jsonb,
     'Distance in centimetres', 3),
    -- Week 10: Actuators
    (10, 2, 'Servo power', 'When does a servo need its own power supply?',
     'developing', array['servo', 'power'],
     array['Light test loads are fine on 5V.', 'Real loads need more current.'],
     'Pushing a real load draws more current, so the servo needs its own supply.', 'multiple_choice',
     '["When it pushes a real load", "When it sits at 0 degrees", "When it is unplugged", "When it is in setup()"]'::jsonb,
     'When it pushes a real load', 1),
    (10, 2, 'Motors and logic pins', 'True or false: a DC motor should never be driven directly from a microcontroller logic pin.',
     'beginner', array['motors', 'drivers'],
     array['Logic pins carry tiny current.', 'Motors need a driver.'],
     'Motors need a driver and PWM; hanging one off a logic pin can damage the board.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (10, 2, 'What write does', 'What does write do on a servo object?',
     'beginner', array['Servo', 'write'],
     array['It takes an angle.', 'It moves the horn.'],
     'write moves the servo to the angle you pass, such as 90 degrees.', 'multiple_choice',
     '["Moves it to an angle you pass", "Erases its program", "Reads a button", "Plays a tone"]'::jsonb,
     'Moves it to an angle you pass', 3),
    -- Week 11: Irrigation
    (11, 2, 'Why average readings', 'Why average several soil readings before deciding to water?',
     'developing', array['averaging', 'robustness'],
     array['One bad reading could be noise.', 'Smoothing beats reacting instantly.'],
     'Averaging a few samples stops one erratic reading from flipping the pump.', 'multiple_choice',
     '["One bad reading should not flip the pump", "To make the sketch longer", "To save memory", "To avoid setup()"]'::jsonb,
     'One bad reading should not flip the pump', 1),
    (11, 2, 'Rapid toggling', 'True or false: a pump that clicks on and off instantly will wear out fast.',
     'beginner', array['debouncing', 'safety'],
     array['Rapid changes stress parts.', 'Patience protects hardware.'],
     'Add minimum pump time and a soak delay so the pump does not thrash.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (11, 2, 'Pump power', 'The pump should run from a relay mostly because of what?',
     'developing', array['relay', 'power separation'],
     array['The Arduino only gives a logic signal.', 'Pumps draw heavier current.'],
     'A relay isolates the pump high-power circuit from the delicate Arduino logic signals.', 'multiple_choice',
     '["Separate high-power supply and safe isolation", "The Arduino has too much free time", "The relay makes beeping sounds", "Relays are cheaper than wires"]'::jsonb,
     'Separate high-power supply and safe isolation', 3),
    -- Week 12: Feeder / millis
    (12, 2, 'Why not delay', 'What problem does delay() cause in a timed feeder?',
     'developing', array['millis', 'responsive loops'],
     array['delay stops everything.', 'Buttons get ignored.'],
     'delay() blocks the whole loop, so the feeder ignores buttons and sensors while waiting.', 'multiple_choice',
     '["It blocks the whole loop so buttons and sensors are ignored", "It makes the clock run fast", "It needs WiFi", "It stops the compiler"]'::jsonb,
     'It blocks the whole loop so buttons and sensors are ignored', 1),
    (12, 2, 'Timestamp timing', 'True or false: using millis() lets a sketch time events while keeping the loop responsive.',
     'beginner', array['millis', 'timers'],
     array['It compares elapsed time.', 'The loop keeps running.'],
     'Comparing millis() values times events without ever blocking the loop.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (12, 2, 'Manual override', 'What should an override button do after forcing a feed?',
     'developing', array['override', 'timers'],
     array['Schedules should stay honest.', 'Timer bookkeeping avoids surprise feeds.'],
     'The override should also move the last-feed timer so the automatic schedule stays sensible.', 'multiple_choice',
     '["Move the last-feed timer so the automatic time updates too", "Forget the timer entirely", "Shut the whole unit down", "Print the source code"]'::jsonb,
     'Move the last-feed timer so the automatic time updates too', 3),
    -- Week 13: Movement primitives
    (13, 2, 'Movement first', 'Why test each movement primitive alone before adding sensors?',
     'developing', array['movement', 'testing'],
     array['Predictable motion comes first.', 'Sensors only add to that base.'],
     'A robot that cannot move predictably cannot react to anything it senses.', 'multiple_choice',
     '["A robot that cannot move predictably cannot react to anything", "To make the code shorter", "Because sensors are cheap", "It makes the wheels spin faster"]'::jsonb,
     'A robot that cannot move predictably cannot react to anything', 1),
    (13, 2, 'Driving straight', 'True or false: to drive straight, both drive wheels usually need matching speed, with a small offset to fix drift.',
     'developing', array['straight line', 'PWM tuning'],
     array['Wheels can differ slightly.', 'Watch over a couple of metres.'],
     'Matching PWM keeps the robot straight; a small offset corrects any drift.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (13, 2, 'End of a move', 'What should happen at the end of a movement primitive call?',
     'beginner', array['movement primitives', 'stop'],
     array['Leave a safe state.', 'Write speed to zero.'],
     'Movement functions should stop the motors, usually by writing speed 0.', 'multiple_choice',
     '["The motors stop, usually by writing speed 0", "The motors keep spinning forever", "The battery is unplugged", "The code jumps to the end of the file"]'::jsonb,
     'The motors stop, usually by writing speed 0', 3),
    -- Week 14: Wiring debug
    (14, 2, 'Backwards robot', 'The robot drives backwards when you asked for forward. What is the fastest fix?',
     'developing', array['wiring', 'polarity'],
     array['The physical wiring differs.', 'Swapping wires beats rewriting code.'],
     'Swap that motor drive wires (the physical pair) rather than rewriting the program.', 'multiple_choice',
     '["Swap that motor drive wires", "Rewind the whole program", "Change the battery first", "Add more code comments"]'::jsonb,
     'Swap that motor drive wires', 1),
    (14, 2, 'Opposing motors', 'True or false: motors on opposite sides face opposite directions, so their forward pins must be labelled per side.',
     'developing', array['motor directions', 'labelling'],
     array['Mounting flips the direction.', 'Labels must match reality.'],
     'Motors are mounted facing opposite ways, so forward pins differ per side.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (14, 2, 'Debug order', 'Which order is right when nothing moves?',
     'developing', array['debug order', 'diagnostics'],
     array['Power first.', 'Then enables, then pins.'],
     'Check power, then enable pins, then input pins, then code, in that order.', 'multiple_choice',
     '["Power, then enable pins, then input pins", "Code, then power, then nothing", "Unscrew everything", "Buy a new robot"]'::jsonb,
     'Power, then enable pins, then input pins', 3),
    -- Week 15: Remote control
    (15, 2, 'Default case', 'What should the default case of a command switch do?',
     'developing', array['switch', 'safety'],
     array['Unknown commands exist.', 'The safe move is stopping.'],
     'The default case should stop the robot safely for unknown or unexpected codes.', 'multiple_choice',
     '["Stop the robot safely", "Speed up", "Turn left", "Keep doing what it was doing"]'::jsonb,
     'Stop the robot safely', 1),
    (15, 2, 'Raw codes first', 'True or false: print the raw incoming code before mapping it so you know what buttons send.',
     'developing', array['decoding', 'serial echo'],
     array['Different remotes send different codes.', 'Print before you map.'],
     'Echoing raw codes to Serial first reveals exactly what each button sends.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (15, 2, 'Mapping input to output', 'Which statement maps a command code to a movement?',
     'developing', array['mapping', 'switch'],
     array['Each code gets one action.', 'Movement happens through functions.'],
     'A switch case calls a movement function such as moveForward for each code.', 'multiple_choice',
     '["A switch case calling a movement function", "A delay call", "A pinMode call", "A comment line"]'::jsonb,
     'A switch case calling a movement function', 3),
    -- Week 16: Obstacle robot
    (16, 2, 'Very close', 'When the robot is very close to an obstacle, what should it do?',
     'developing', array['obstacle avoidance', 'reaction'],
     array['Do not drive into it.', 'Back away first.'],
     'Very close means reverse then turn away instead of charging forward.', 'multiple_choice',
     '["Reverse and then turn away", "Speed straight on", "Ignore it", "Flash the LED"]'::jsonb,
     'Reverse and then turn away', 1),
    (16, 2, 'Scanning sides', 'True or false: scanning left then right before turning lets the robot choose the emptier side.',
     'developing', array['scanning', 'choices'],
     array['Gather information first.', 'Pick the larger gap.'],
     'Scanning both sides and choosing the larger gap makes avoidance smarter.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (16, 2, 'Good thresholds', 'Where do good avoidance thresholds come from?',
     'developing', array['thresholds', 'tuning'],
     array['Real runs teach you.', 'Measure, then tune.'],
     'Record real approach distances and set thresholds from those measurements.', 'multiple_choice',
     '["Real recorded approach distances", "The thickness of the manual", "A random guess", "The robot colour"]'::jsonb,
     'Real recorded approach distances', 3),
    -- Week 17: State machines
    (17, 2, 'One active state', 'What is the rule for a state machine?',
     'developing', array['state machines', 'design'],
     array['Exactly one state rules.', 'Transitions move between them.'],
     'A state machine keeps exactly one state active at any moment.', 'multiple_choice',
     '["One state is active at any time", "All states run together", "States cannot be named", "Only two states ever exist"]'::jsonb,
     'One state is active at any time', 1),
    (17, 2, 'Draw first', 'True or false: drawing the states and arrows before coding prevents tangled logic.',
     'developing', array['design first', 'state machines'],
     array['The diagram is the design.', 'Coding comes after.'],
     'Sketching states and transitions first exposes tangled logic before it is coded.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (17, 2, 'Naming the states', 'What piece of code names the states of a state machine?',
     'developing', array['enum', 'switch'],
     array['Names come from a type.', 'A switch walks the states.'],
     'An enum names the states and a switch on it walks through them.', 'multiple_choice',
     '["An enum and a switch", "A delay and a loop", "A comment and a blank line", "A float variable"]'::jsonb,
     'An enum and a switch', 3),
    -- Week 18: Mopping robot
    (18, 2, 'Lane sweep', 'Why prefer a lane-sweep pattern over random wandering?',
     'developing', array['coverage patterns', 'planning'],
     array['Planned motion covers everything.', 'Randomness leaves gaps.'],
     'A planned lane sweep covers every strip without the gaps of random motion.', 'multiple_choice',
     '["It covers the whole area without gaps", "It looks exciting", "It uses less battery", "It avoids turning"]'::jsonb,
     'It covers the whole area without gaps', 1),
    (18, 2, 'Payload effects', 'True or false: adding a mop payload changes the robot traction and turn timing.',
     'developing', array['payload', 'calibration'],
     array['Weight changes grip.', 'Retest after attaching.'],
     'A heavier mop changes wheel traction, so re-measure turns and speed with it attached.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (18, 2, 'Getting stuck', 'What should the mopping robot do if it gets stuck?',
     'developing', array['safety', 'stall detection'],
     array['Do not grind forever.', 'Stop cleanly.'],
     'Detect a stall and stop gracefully rather than dragging or grinding.', 'multiple_choice',
     '["Stop gracefully and report", "Push harder forever", "Repeat random bumps", "Stop only after a full minute"]'::jsonb,
     'Stop gracefully and report', 3),
    -- Week 19: Soccer robot
    (19, 2, 'Before pushing', 'Before pushing the ball, what should the robot do?',
     'developing', array['chase logic', 'centering'],
     array['Align first.', 'Push square, not angled.'],
     'Centre the ball in the sensor before pushing so the push is straight.', 'multiple_choice',
     '["Centre the ball in its sensor", "Run at full speed no matter what", "Turn away", "Play a sound"]'::jsonb,
     'Centre the ball in its sensor', 1),
    (19, 2, 'One change at a time', 'True or false: changing scan speed and chase speed in the same test makes it hard to know what helped.',
     'developing', array['iteration', 'controlled tests'],
     array['Change one thing at a time.', 'That isolates the cause.'],
     'One change per test makes it clear which tuning helped the robot.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (19, 2, 'Ball lost', 'When the ball is lost, what should the robot do?',
     'developing', array['scanning', 'chase logic'],
     array['Regain the target.', 'Avoid blind driving.'],
     'The robot should scan to find the ball instead of blindly driving into a wall.', 'multiple_choice',
     '["Scan to find it, not blindly drive into a wall", "Keep driving straight forever", "Recharge", "Stop all motion permanently"]'::jsonb,
     'Scan to find it, not blindly drive into a wall', 3),
    -- Week 20: Robotics challenge
    (20, 2, 'Preparation beats luck', 'In the Robotics Challenge, what beats raw skill?',
     'developing', array['checklists', 'preparation'],
     array['A routine catches faults.', 'The clock rewards readiness.'],
     'A reliable pre-run routine and calm preparation prevent disasters on the course.', 'multiple_choice',
     '["Preparation and a reliable routine", "Raw luck", "Bigger wheels", "Louder sounds"]'::jsonb,
     'Preparation and a reliable routine', 1),
    (20, 2, 'Practice runs', 'True or false: running a practice attempt and logging failures is useful feedback, not a judgement on you.',
     'developing', array['practice', 'feedback'],
     array['Failures are data.', 'Fix and retry.'],
     'Practice logs are data: each failure points to one fix on the next run.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (20, 2, 'Pre-run checklist', 'What should a pre-run checklist cover?',
     'developing', array['checklists', 'preparation'],
     array['Start with power.', 'Finish with movement.'],
     'A checklist covers power, wiring, a sensor self-test, and a movement check.', 'multiple_choice',
     '["Power, wiring, sensor self-test, movement", "Only the battery", "The team names", "The font of the notes"]'::jsonb,
     'Power, wiring, sensor self-test, movement', 3),
    -- Week 21: ESP32 WiFi
    (21, 2, 'Connection proof', 'What is the visible proof that an ESP32 joined your network?',
     'developing', array['ESP32', 'WiFi'],
     array['The device gets an address.', 'That address prints.'],
     'Printing the assigned IP address is real, visible proof the device is online.', 'multiple_choice',
     '["Its printed IP address", "A green sticker", "The rising temperature", "A louder fan"]'::jsonb,
     'Its printed IP address', 1),
    (21, 2, 'Wait to connect', 'True or false: wait for an active WiFi connection before publishing sensor data.',
     'beginner', array['WiFi', 'connection states'],
     array['Check status first.', 'Publish after connecting.'],
     'Connect to WiFi and wait for WL_CONNECTED before sending data.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (21, 2, 'Secret credentials', 'Why keep WiFi passwords out of the shared sketch?',
     'developing', array['secrets', 'security'],
     array['Shared code is public.', 'Leaks spread quickly.'],
     'Secrets in committed code leak when the sketch or repository is shared.', 'multiple_choice',
     '["Secrets in code can leak when it is shared", "It makes the code shorter only", "The password cannot be a word", "Compilation is slower"]'::jsonb,
     'Secrets in code can leak when it is shared', 3),
    -- Week 22: Security state machine
    (22, 2, 'Triggered state', 'In a security alarm, what should the TRIGGERED state do?',
     'developing', array['state machines', 'security'],
     array['Alarm on intrusion.', 'Silence when disarmed.'],
     'TRIGGERED sounds the alarm until it is disarmed and cleared.', 'multiple_choice',
     '["Sound the alarm until it is disarmed", "Ignore all motion", "Stay silent forever", "Turn off the keypad"]'::jsonb,
     'Sound the alarm until it is disarmed', 1),
    (22, 2, 'Test every transition', 'True or false: every transition of a state machine deserves a named test case.',
     'developing', array['testing', 'transitions'],
     array['Arrows are behaviours.', 'Untested arrows are hazards.'],
     'Walk and name each transition so every behaviour is proven once.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (22, 2, 'Transition matrix', 'Which transition walk should you test carefully?',
     'challenge', array['security logic', 'transitions'],
     array['Round trips matter.', 'Arm, trigger, disarm.'],
     'Walk the loop arm to trigger to disarm to arm again to prove it survives a full cycle.', 'multiple_choice',
     '["Arm to trigger to disarm to arm again", "Just arm and never touch it", "Only the WiFi phase", "Only the buzzer once"]'::jsonb,
     'Arm to trigger to disarm to arm again', 3),
    -- Week 23: Capstone design
    (23, 2, 'Sharp problem statement', 'What makes a capstone problem statement sharp?',
     'challenge', array['problem framing', 'design'],
     array['Name a user and a need.', 'State a measurable test.'],
     'A sharp statement names a user, a need, and a measurable success criterion.', 'multiple_choice',
     '["A user, a need, and a measurable success criterion", "A long list of parts", "A famous name", "A long video"]'::jsonb,
     'A user, a need, and a measurable success criterion', 1),
    (23, 2, 'Milestones and tests', 'True or false: a milestone without a test is just a wish.',
     'challenge', array['milestones', 'planning'],
     array['Progress must be provable.', 'Tests make milestones real.'],
     'Pair every milestone with a completion test so progress is provable.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (23, 2, 'Scope control', 'Why limit the capstone scope?',
     'challenge', array['scope', 'delivery'],
     array['Small and finished wins.', 'Broken giants lose.'],
     'A small finished system beats a big broken one, so constrain inputs, decision, and outputs.', 'multiple_choice',
     '["Small and finished beats big and broken", "Engineers dislike work", "Parts are always free", "Loops are infinite"]'::jsonb,
     'Small and finished beats big and broken', 3),
    -- Week 24: Final test & demo
    (24, 2, 'Run it twice', 'Why run the requirement checklist twice?',
     'challenge', array['testing', 'repeatability'],
     array['One pass could be luck.', 'A second pass proves repeatability.'],
     'A second pass proves the result is repeatable and not a lucky once-off.', 'multiple_choice',
     '["The second pass proves the result is repeatable", "Because lists fall apart once", "To fill the time", "To show the panel two shows"]'::jsonb,
     'The second pass proves the result is repeatable', 1),
    (24, 2, 'Documented fixes', 'True or false: a documented failure and its fix is worth more than a lucky success.',
     'challenge', array['documentation', 'engineering'],
     array['Evidence teaches.', 'Lucky passes teach nothing.'],
     'A debug log with a failure and fix is evidence and counts more than luck.', 'true_false',
     '["true", "false"]'::jsonb,
     'true', 2),
    (24, 2, 'Demo answers', 'A three-minute demo should answer what, in order?',
     'challenge', array['demo', 'communication'],
     array['The problem, then how it works.', 'End with what changed.'],
     'Answer the problem, the SENSE-THINK-ACT design, what testing found, and the next improvement.', 'multiple_choice',
     '["The problem, the design flows, what testing found, next improvement", "Only the LED colours", "The cost of the robot", "Who built it first"]'::jsonb,
     'The problem, the design flows, what testing found, next improvement', 3)
) as exercise(week_number, lesson_number, title, instructions, difficulty, expected_concepts, hints, explanation, question_type, choices, correct_answer, sort_order)
  on exercise.week_number = weeks.week_number
  and lessons.lesson_number = exercise.lesson_number
where course.slug = 'cpp-embedded-robotics'
  and not exists (
    select 1 from public.academy_exercises existing
    where existing.lesson_id = lessons.id and existing.title = exercise.title
  );